name: Update yfinance data

on:
  push:
    paths:
      - 'yfinance_data/**'
  workflow_dispatch:

# Grant write access to push changes
permissions:
  contents: write

jobs:
  update-data:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: pip install -r yfinance_data/requirements.txt
      - name: Test with unittest
        run: python -m unittest yfinance_data/test_fetch_data.py
      - name: Run data fetching script
        run: python yfinance_data/fetch_data.py --webhook-url "${{ secrets.YFINANCE_WEBHOOK_URL }}"
      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Update yfinance data"
          file_pattern: "yfinance_data/yfinance.dat"
